#!/bin/bash
# Bootstrap script - runs at container startup to verify and repair tool installation
# This is a safety net to catch any missing tools before the bot starts

set -e

echo "=== BOOTSTRAP: Checking required tools ==="

# Tool inventory - add new tools here
REQUIRED_TOOLS=(
    "openclaw:openclaw --version:npm install -g openclaw@2026.2.3-1"
    "rsync:rsync --version:apt-get install -y rsync"
    "git:git --version:apt-get install -y git"
    "curl:curl --version:apt-get install -y curl"
)

# Track missing tools for reporting
MISSING_TOOLS=()
REINSTALLED_TOOLS=()

check_and_install() {
    local name="$1"
    local check_cmd="$2"
    local install_cmd="$3"
    
    echo -n "  Checking $name... "
    
    if eval "$check_cmd" > /dev/null 2>&1; then
        echo "OK"
        return 0
    else
        echo "MISSING - installing..."
        MISSING_TOOLS+=("$name")
        
        if eval "$install_cmd" > /dev/null 2>&1; then
            echo "  -> $name installed successfully"
            REINSTALLED_TOOLS+=("$name")
            return 0
        else
            echo "  -> FAILED to install $name"
            return 1
        fi
    fi
}

# Check each tool
for tool_spec in "${REQUIRED_TOOLS[@]}"; do
    IFS=':' read -r name check_cmd install_cmd <<< "$tool_spec"
    check_and_install "$name" "$check_cmd" "$install_cmd" || true
done

echo ""
echo "=== BOOTSTRAP: Summary ==="

if [ ${#MISSING_TOOLS[@]} -eq 0 ]; then
    echo "All tools present and accounted for."
else
    echo "Tools that were missing: ${MISSING_TOOLS[*]}"
    if [ ${#REINSTALLED_TOOLS[@]} -gt 0 ]; then
        echo "Tools reinstalled: ${REINSTALLED_TOOLS[*]}"
    fi
fi

# Write status to a file the bot can read
TOOLS_STATUS_FILE="/root/clawd/.tools-status"
cat > "$TOOLS_STATUS_FILE" << EOF
# Tool Status (generated by bootstrap.sh)
# Last check: $(date -Iseconds)

## Status
$(if [ ${#MISSING_TOOLS[@]} -eq 0 ]; then echo "ALL_OK"; else echo "HAD_ISSUES"; fi)

## Missing at startup
$(if [ ${#MISSING_TOOLS[@]} -eq 0 ]; then echo "None"; else printf '%s\n' "${MISSING_TOOLS[@]}"; fi)

## Reinstalled
$(if [ ${#REINSTALLED_TOOLS[@]} -eq 0 ]; then echo "None"; else printf '%s\n' "${REINSTALLED_TOOLS[@]}"; fi)
EOF

echo ""
echo "Status written to $TOOLS_STATUS_FILE"
echo "=== BOOTSTRAP: Complete ==="
